<?php

namespace Database\Seeders;

use App\Http\Modules\Services\Models\CategoryService;
use App\Http\Modules\Services\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategoryServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $items = [
            'Reparación de motor',
            'Reparación de Transfer',
            'Cambio de inyectores',
            'Reparación transmisión',
            'Servicio de scaner',
            'Cambio de muelles traseros',
            'Cambio de muelle delantero',
            'Cambio de embrague',
            'Raparacion parte eléctrica del equipo',
            'Evaluacion sistema de Inyeccion',
            'Evaluacion sistema de Refrigeracion / Enfriamiento',
            'Desmonte y monte de culata',
            'Reparacion de culata (Rectificadora) con prueba en banco',
            'Cambio de una linea de potencia (camisa y piston)',
            'Cambio de un inyector',
            'Cambio de arnes de inyectores',
            'Cambio de bomba de alta',
            'Cambio de Valvula IPR',
            'Cambio de sensor ICP',
            'Cambio de sensor CPM',
            'Cambio bomba de agua',
            'Cambio de empaque de galeria de alta',
            'Desmonte y monte enfriador de aceite',
            'Cambio de empaque del carter',
            'Desmoste y monte de ECM',
            'Programacion ECM',
            'Cambio de sellos enfriador de aceite',
            'Cambio de camisillas linea de combustible',
            'Reparacion del Fan clutch',
            'Desmonte y monte de tapa frontales de motor',
            'Reparacion de tapas frontal trasera',
            'Reparacion de tapas frontal delantera',
            'Cambio de bomba de aceite',
            'Cambio de correa del motor',
            'Cambio de correa del alternador',
            'Cambio de correa del sistema de aire acondicionado',
            'Desmonte y monte de radiador',
            'Desmotaje y montaje del Modulo ESC',
            'Cambio de tanque auxiliar de refrigerante',
            'Reparacion de Enfriador de aceite',
            'Calibración motor',
            'Cambio soporte de motor',
            'Desmonte y monte bomba de combustible',
            'Desmonte y monte turbocargador',
            'Reparación turbocargador',
            'Desmonte y monte riel de inyección',
            'Reparación de pito, alarma de reversa y limpiaparabrisas',
            'Reparación de luces generales (luces de cabina, direccionales, de freno, reversa, etc.)',
            'Diagnóstico y reparación de códigos de motor (ECM)',
            'Diagnóstico de freno de ahogo y motor',
            'Reparación de alternadores',
            'Reparación de motor de arranque',
            'Reparación tableros de instrumentos',
            'Reparación módulos del motor',
            'Reparación módulos de cabina',
            'Reparación de bornes y cableado de baterías',
            'Mtto baterías 30H',
            'Mtto baterías 31T',
            'Cambio de batería 30H',
            "Cambio de batería 31T",
            "Cambio de Muelles delanteros",
            "Cambio de muelles traseros",
            "Cambio de buje de vigas tanden",
            "Cambio de buje barra tensora",
            "Cambio de barra tensora",
            "desmonte y monte de vigas tanden",
            "Cambio de Amortiguadores",
            "Cambio de fuelles",
            "Reparacion de hausen.",
            "Reparacion de diferenciales",
            "Diagnóstico de accionamiento de embrague",
            "Cambio de embrague",
            "Reparacion de media caja",
            "Reparacion caja transmisión de velocidades",
            "Reparacion y/o cambio de PTO",
            "Cambio de sello de cigüeñal trasero",
            "cambio soporte cardan",
            "Cambio de crucetas eje cardan",
            "Reparacion Eje cardan intermedio (cambio de punta y botella)",
            "Reparacion Eje cardan principal (cambio de punta y botella)",
            "Cambio del retenedor del yokey",
            "Cambio de Recamara de freno delantero",
            "Cambio de Recamara de freno",
            "Remache de zuncho de bandas de freno",
            "Cambio de bandas de frenos delanteros",
            "Cambio de raches de frenos",
            "Cambio de campana de frenos",
            "Cambio de rodamientos interno y externo",
            "Cambio de retenedores rueda delantera",
            "Cambio de retenedores rueda trasera",
            "Cambio de bandas de frenos Traseros",
            "Cambio de valvula de Freno / Aire",
            "cambio de manguera y tuberia de aire de frenos",
            "Cambio de manguera de Frenos",
            "Cambio tanques de Aire de servicio",
            "Reparacion de Botella de Direccion (cambio de sellos)",
            "Desmonte y monte botella de dirección",
            "Cambio de Bomba de direccion",
            "Cambio de terminales de direccion",
            "Cambio de Brazo de direccion",
            "Cambio de cruceta caña de direccion",
            "cambio Barra de direccion",
            "cambio de brazo pigman",
            "Cambio deposito liquido de freno",
            "Cambio de mangueras de direccion",
            "Cambio de mangueras de aire acondicionado",
            "Cambio de compresor sistema de aire acondicionado",
            "Cambio de condensador",
            "Flushing al condensador",
            "Cambio de filtro secador del aire acondicionado",
            "Mantenimiento correctivo flushing al evaporador",
            "Cambio de evaporador",
            "Reparacion de Motor",
            "Evaluacion de Motor",
            "Evaluacion sistema de Inyeccion",
            "Evaluacion sistema de Refrigeracion / Enfriamiento",
            "Mantenimiento corretivo Sistema de enfriamiento",
            "Reparacion sistema Inyeccion",
            "Reparacion de Alternador",
            "Reparacion de arranque",
            "Reparacion de Cableado eléctrico",
            "cambio de caja fusibles",
            "Cambio de pilas de caja de fusibles",
            "Cambio de sensores eléctricos",
            "Cambio de sensores de temperatura",
            "cambio de sensores de presión",
            "Reparacion y/o cambio de compuertas",
            "Reparacion y/o cambio de luces y farolas",
            "Reparacion y/o cambio de interruptores",
            "Reparacion y/o cambio de bocinas",
            "Reparacion y/o cambio de switch de encendido",
            "Reparacion y/o cambio de relays",
            "Reparacion y/o cambio de ventiladores",
            "Reparacion y/o cambio de solenoides",
            "Cambio de piñones de ataque",
            "Cambio de piñones de caja",
            "Cambio de sello frontal y trasero de eje trasero",
            "Cambio de guardapolvos de eje trasero",
            "Cambio de soporte de punta de ejes",
            "Cambio de retenedores de eje trasero",
            "Reparacion y/o cambio de punta de eje",
            "Cambio de retenedores de eje delantero",
            "Cambio de guardapolvos de eje delantero",
            "Cambio de soporte de punta de eje",
            "Cambio de retenedores de eje delantero",
            "Reparacion y/o cambio de punta de eje",
            "Cambio de buje de rueda delantera",
            "Cambio de buje de rueda trasera",
            "Cambio de caja de transmisión",
            "Cambio de sello de cigüeñal delantero",
            "Cambio de valvula de Descompresion",
            "Reparacion de Válvulas de Cilindros",
            "Cambio de sello de cigüeñal trasero",
            "Cambio de Anillos de Cilindros",
            "Cambio de Bomba de agua",
            "Cambio de Kit de Embrague",
            "Cambio de Kit de distribución",
            "Cambio de Amortiguadores",
            "Cambio de Barras estabilizadoras",
            "Cambio de Brazo de suspensión",
            "Cambio de Bujes de suspensión",
            "Cambio de Fuelles",
            "Cambio de Kit de rodamientos",
            "Cambio de Rótulas de suspensión",
            "Cambio de Soportes de motor",
            "Cambio de Terminal de suspensión",
            "Reparacion de compuertas",
            "Reparacion de tapas",
            "Reparacion de botones",
            "Reparacion de bisagras",
            "Reparacion de manijas",
            "Reparacion de cerraduras",
            "Reparacion de ventanas",
            "Reparacion de seguros",
            "Reparacion de espejos retrovisores",
            "Reparacion de parabrisas",
            "Cambio de parabrisas",
            "Cambio de vidrios laterales",
            "Cambio de vidrios traseros",
            "Cambio de fachadas",
            "Cambio de forros",
            "Cambio de paneles de puertas",
            "Cambio de farolas",
            "Cambio de luces",
            "Cambio de emblemas",
            "Cambio de parrillas",
            "Cambio de bumpers",
            "Cambio de defensas",
            "Cambio de estribos",
            "Cambio de guardafangos",
            "Cambio de capo",
            "Cambio de maletero",
            "Cambio de parachoque",
            "Cambio de radiador",
            "Cambio de ventilador",
            "Cambio de sistema de enfriamiento",
            "Cambio de sistema de escape",
            "Cambio de catalizador",
            "Cambio de resonador",
            "Cambio de tubo de escape",
            "Cambio de silenciador",
            "Cambio de flexibles",
            "Cambio de abrazaderas",
            "Cambio de aislantes",
            "Cambio de colectores",
            "Cambio de carburador",
            "Cambio de sistema de inyección",
            "Cambio de sensores de oxígeno",
            "Cambio de sensores de presión",
            "Cambio de sensores de temperatura",
            "Cambio de sensores de flujo de aire",
            "Cambio de sensores de posición de árbol de levas",
            "Cambio de sensores de posición de cigüeñal",
            "Cambio de sensores de detonación",
            "Cambio de bobinas",
            "Cambio de cables de bujía",
            "Cambio de bujías",
            "Cambio de motor de arranque",
            "Cambio de alternador",
            "Cambio de batería",
            "Cambio de fusibles",
            "Cambio de luces",
            "Cambio de bocinas",
            "Cambio de reproductor de audio",
            "Cambio de sistema de navegación",
            "Cambio de pantallas",
            "Cambio de cámaras de retroceso",
            "Cambio de sensores de estacionamiento",
            "Cambio de sensores de lluvia",
            "Cambio de sensores de luz",
            "Cambio de sensores de temperatura",
            "Cambio de sensores de presión de neumáticos",
            "Cambio de interruptores",
            "Cambio de actuadores",
            "Cambio de sensores de control de crucero",
            "Cambio de sensores de control de estabilidad",
            "Cambio de sensores de control de tracción",
            "Cambio de sensores de freno",
            "Cambio de caja de cambios",
            "Cambio de embrague",
            "Cambio de palanca de cambios",
            "Cambio de sensores de velocidad",
            "Cambio de sensores de posición",
            "Cambio de actuadores",
            "Cambio de motor del limpiaparabrisas",
            "Cambio de brazos del limpiaparabrisas",
            "Cambio de escobillas del limpiaparabrisas",
            "Cambio de mangueras de lavaparabrisas",
            "Cambio de depósito de líquido de lavaparabrisas",
            "Cambio de bomba de líquido de lavaparabrisas",
            "Cambio de radiador",
            "Cambio de termostato",
            "Cambio de ventilador",
            "Cambio de bomba de agua",
            "Cambio de correas",
            "Cambio de poleas",
            "Cambio de tensores",
            "Cambio de sistema de dirección",
            "Cambio de bomba de dirección asistida",
            "Cambio de mangueras de dirección",
            "Cambio de terminales de dirección",
            "Cambio de rótulas de dirección",
            "Cambio de brazos de dirección",
            "Cambio de barras de dirección",
            "Cambio de caja de dirección",
            "Cambio de fuelles de dirección",
            "Cambio de amortiguadores de dirección",
            "Cambio de frenos",
            "Cambio de discos de freno",
            "Cambio de pastillas de freno",
            "Cambio de calipers",
            "Cambio de cilindros de freno",
            "Cambio de mangueras de freno",
            "Cambio de líquido de freno",
            "Cambio de cilindro maestro de freno",
            "Cambio de servo de freno",
            "Cambio de válvula de freno",
            "Cambio de latiguillos de freno",
            "Cambio de ABS",
            "Cambio de sistema de suspensión",
            "Cambio de amortiguadores",
            "Cambio de resortes",
            "Cambio de bujes",
            "Cambio de rótulas",
            "Cambio de terminales",
            "Cambio de barras estabilizadoras",
            "Cambio de brazos de suspensión",
            "Cambio de bujes de horquilla",
            "Cambio de fuelles",
            "Cambio de bujes de estabilizadores",
            "Cambio de cojinetes de rueda",
            "Cambio de neumáticos",
            "Cambio de alineación y balanceo",
            "Cambio de llantas",
            "Cambio de válvulas",
            "Cambio de bujes de válvulas",
            "Cambio de guías de válvulas",
            "Cambio de sellos de válvulas",
            "Cambio de retenes de válvulas",
            "Cambio de resortes de válvulas",
            "Cambio de cadena de distribución",
            "Cambio de piñones de distribución",
            "Cambio de tensores de distribución",
            "Cambio de correa de distribución",
            "Cambio de poleas de distribución",
            "Cambio de bomba de aceite",
            "Cambio de filtro de aceite",
            "Cambio de tapa de aceite",
            "Cambio de tapa de filtro de aceite",
            "Cambio de junta de cárter",
            "Cambio de cárter",
            "Cambio de tornillos de cárter",
            "Cambio de sensor de aceite",
            "Cambio de sensor de nivel de aceite",
            "Cambio de sensor de presión de aceite",
            "Cambio de culata",
            "Cambio de junta de culata",
            "Cambio de bujías de precalentamiento",
            "Cambio de calentadores",
            "Cambio de sensor de temperatura de motor",
            "Cambio de sensor de temperatura de refrigerante",
            "Cambio de radiador de aceite",
            "Cambio de enfriador de aceite",
            "Cambio de termostato",
            'Cambio de condensador',
            'Flushing al condensador',
            'Cambio de filtro secador del aire acondicionado',
            'Mantenimiento correctivo flushing al evaporador',
            'Cambio de evaporador',
            'Reparacion de Motor',
            'Evaluacion de Motor',
            'Evaluacion sistema de Inyeccion',
            'Evaluacion sistema de Refrigeracion / Enfriamiento',
            'Mantenimiento corretivo Sistema de enfriamiento',
            'Reparacion sistema Inyeccion',
            'Desmonte y monte de culata',
            'Reparacion de culata (Rectificadora)',
            'Cambio de una linea de potencia (camisa y piston)',
            'Cambio de un inyector',
            'Cambio de los 6 inyectores',
            'cambio de arnes de inyectores',
            'Cambio de bomba de alta',
            'Cambio de Valvula IPR',
            'Cambio de sensor ICP',
            'Cambio de sensor CPM',
            'Cambio bomaba de agua',
            'desmonte y monte de galeria de alta',
            'desmonte y monte enfriador de aceite',
            'cambio de empaque del carter',
            'desmonte y monte de ECM',
            'Programacion ECM',
            'Cambio de sellos enfriador de aceite',
            'Cambio de camisillas linea de combustible',
            'Reparacion del Fan clutch',
            'Desmonte y monte de tapa frontales de motor',
            'Reparacion de tapas frontal trasera',
            'Reparacion de tapas frontal delantera',
            'Cambio de bomba de aceite',
            'Mtto sistema de trasmision del motor(correa de motor, poleas)',
            'Cambio y/o lavado de radiador',
            'Desmotaje y montaje del Modulo ESC',
            'Reparcion y/o cambio de tanque de refrigerante',
            'Reparacion de Enfriador',
            'Calibracion de Valvula.',
            'Mantenimineto correctivo bomba de inyeccion e inyectores.',
            'Mantenimineto general motor (cambio de soportes)',
            'Reparacion sistema de inyeccion, bombas de combustible, inyectores, riel de inyeccion, turbocargador',
            'Reparacion de control, direccionales, tablero de instrumentos de control, testigos, de Luces Generales. (luces de cabina, direcionales, de freno, reversa, etc.), pito, alarma de reverza, Funcionamiento de limpiabrisas',
            'Diagnostico de codigos de motor (ECM) y Lecturas de codigo electricos (ESC), freno de ahogo y motor / juego de pedal de freno',
            'Accionamiento de embrague',
            'Reparacion de altenadores, motores de arranque, tableros de instrumentos, modulos de motor, modulos de cabina, Baterias, bornes y cableado',
            'Cambio de Muelles delanteros',
            'Cambio de muelles traseros',
            'Cambio de buje de vigas tanden.',
            'Cambio de condensador',
            'Flushing al condensador',
            'Cambio de filtro secador del aire acondicionado',
            'Mantenimiento correctivo flushing al evaporador',
            'Cambio de evaporador',
            'Reparacion de Motor',
            'Evaluacion de Motor',
            'Evaluacion sistema de Inyeccion',
            'Evaluacion sistema de Refrigeracion / Enfriamiento',
            'Mantenimiento corretivo Sistema de enfriamiento',
            'Reparacion sistema Inyeccion',
            'Desmonte y monte de culata',
            'Reparacion de culata (Rectificadora)',
            'Cambio de una linea de potencia (camisa y piston)',
            'Cambio de un inyector',
            'Cambio de los 6 inyectores',
            'cambio de arnes de inyectores',
            'Cambio de bomba de alta',
            'Cambio de Valvula IPR',
            'Cambio de sensor ICP',
            'Cambio de sensor CPM',
            'Cambio bomaba de agua',
            'desmonte y monte de galeria de alta',
            'desmonte y monte enfriador de aceite',
            'cambio de empaque del carter',
            'desmoste y monte de ECM',
            'Programacion ECM',
            'Cambio de sellos enfriador de aceite',
            'Cambio de camisillas linea de combustible',
            'Reparacion del Fan clutch',
            'Desmonte y monte de tapa frontales de motor',
            'Reparacion de tapas frontal trasera',
            'Reparacion de tapas frontal delantera',
            'Cambio de bomba de aceite',
            'Mtto sistema de trasmision del motor(correa de motor, poleas)',
            'Cambio y/o lavado de radiador',
            'Desmotaje y montaje del Modulo ESC',
            'Reparcion y/o cambio de tanque de refrigerante',
            'Reparacion de Enfriador',
            'Calibracion de Valvula.',
            'Mantenimineto correctivo bomba de inyeccion e inyectores.',
            'Mantenimineto general motor (cambio de soportes)',
            'Reparacion sistema de inyeccion, bombas de combustible, inyectores, riel de inyeccion, turbocargador',
            'Reparacion de control, direccionales, tablero de instrumentos de control, testigos, de Luces Generales. (luces de cabina, direcionales, de freno, reversa, etc.), pito, alarma de reverza, Funcionamiento de limpiabrisas',
            'Diagnostico de codigos de motor (ECM) y Lecturas de codigo electricos (ESC), freno de ahogo y motor / juego de pedal de freno',
            'Accionamiento de embrague',
            'Reparacion de altenadores, motores de arranque, tableros de instrumentos, modulos de motor, modulos de cabina, Baterias, bornes y cableado',
            'Cambio de Muelles delanteros',
            'Cambio de muelles traseros',
            'Cambio de buje de vigas tanden',
            'Reparacion de vigas tanden',
            "Cambio de condensador",
            "Flushing al condensador",
            "Cambio de filtro secador del aire acondicionado",
            "Mantenimiento correctivo flushing al evaporador",
            "Cambio de evaporador",
            "Reparacion de Motor",
            "Evaluacion de Motor",
            "Evaluacion sistema de Inyeccion",
            "Evaluacion sistema de Refrigeracion / Enfriamiento",
            "Mantenimiento corretivo  Sistema de enfriamiento",
            "Reparacion sistema Inyeccion",
            "Desmonte y monte de culata",
            "Reparacion de culata (Rectificadora)",
            "Cambio de una linea de potencia (camisa y piston)",
            "Cambio de un inyector",
            "Cambio de los 6 inyectores",
            "cambio de arnes de inyectores",
            "Cambio de bomba de alta",
            "Cambio de Valvula IPR",
            "Cambio de sensor ICP",
            "Cambio de sensor CPM",
            "Cambio bomaba de agua",
            "desmonte y monte de galeria de alta",
            "desmonte y monte enfriador de aceite",
            "cambio de empaque del carter",
            "desmoste y monte de ECM",
            "Programacion ECM",
            "Cambio de sellos enfriador de aceite",
            "Cambio de camisillas linea de combustible",
            "Reparacion del Fan clutch",
            "Desmonte y monte de tapa frontales de motor",
            "Reparacion de tapas frontal trasera",
            "Reparacion de tapas frontal delantera",
            "Cambio de bomba de aceite",
            "Mtto sistema de trasmision del motor(correa de motor, poleas)",
            "Cambio y/o lavado de radiador",
            "Desmotaje y montaje del Modulo ESC",
            "Reparcion y/o cambio de tanque de refrigerante",
            "Reparacion de Enfriador",
            "Calibracion de Valvula",
            "Mantenimineto correctivo bomba de inyeccion e inyectores",
            "Mantenimineto general motor (cambio de soportes)",
            "Reparacion sistema de inyeccion, bombas de combustible, inyectores, riel de inyeccion, turbocargador",
            "Reparacion de control, direccionales, tablero de instrumentos de control, testigos, de Luces Generales. (luces de cabina, direcionales, de freno, reversa, etc.), pito, alarma de reverza, Funcionamiento de limpiabrisas",
            "Diagnostico de codigos de motor (ECM) y Lecturas de codigo electricos (ESC), freno de ahogo y motor / juego de pedal de freno",
            "Accionamiento de embrague",
            "Reparacion de altenadores, motores de arranque, tableros de instrumentos, modulos de motor, modulos de cabina, Baterias, bornes y cableado",
            "Cambio de Muelles delanteros",
            "Cambio de muelles traseros",
            "Cambio de buje de vigas tanden",
            "Reparacion de vigas tanden",
            "Cambio de buje barra tensora",
            "Cambio de barran tensoras",
            "Desmonte y monte de vigas tanden",
            "Cambio de Amortiguadores",
            "Cambio de fuelles",
            "Reparacion de hausen",
            "Reparacion de diferenciales",
            "Cambio de embrague",
            "Mantenimiento y/o Graduaccion de embrague",
            "Reparacion de media caja",
            "Reparacion de transmision",
            "Reparacion por fuga ejes laterales, cambio de Bosing. Cambio de esparragos",
            "Cambio de ejes laterales",
            "Reparacion y/o cambio de PTO",
            "Cambio de volanta",
            "Cambio de sello de cigüeñal",
            "cambio soporte cardan",
            "Cambio de crucetas eje cardan",
            "Reparacion Eje cardan",
            "Cambio del retenedor del yokey",
            "Cambio de Recamara de freno delantero",
            "Cambio de Recamara de freno",
            "Remache de zuncho de badas dse freno",
            "Cambio de bandas de frenos delanteros",
            "Cambio de raches de frenos",
            "Cambio de campana",
            "Cambio de rodaminetos interno y externo",
            "Cambio de retenedores rueda delantera",
            "Cambio de retenedores rueda trasera",
            "Cambio de bandas de frenos Traseros",
            "Cambio de valvula de Freno / Aire",
            "cambio de manguera y tuberia de aire",
            "Cambio de manguera de Frenos",
            "Cambio / Reparacion tanques de Aire",
            "Reaparacion de Bases / extructura",
            "Cambio de mangueras de frenos",
            "Evaluacion sistema de freno",
            "Reparacion/ cambio de Botella de Direccion",
            "Reparacion y/o Cambio de Bomba de direccion",
            "Cambio de terminales de direccion",
            "Reparacion y /o Cambio de Brazo de direccion",
            "Cambio de Bomba de direccion",
            "Cambio de cruceta caña de direccion",
            "Reparacion y/o cambio Barra de direccion",
            "cambio de brazo pigman",
            "Cambio deposito liquido de freno",
            "Cambio de mangueras de direccion",
            "Mantenimineto Preventivo Aire Acondicionado",
            "Manatenimiento Correctivo Aire Acondicionado",
            "Mantenimineto Equipo Auxiliar",
            "Cambiar el Filtro de Aire Acondicionado de la cabina",
            "Revisar el selector de velocidades del soplador. Deben servir todas las velocidades del selector",
            "Chequear compresor por ruidos generados, Rodamientos",
            "Limpiar o lavar el condensador exteriormente de suciedad u obstruccion",
            "Evalue estado del filtro secador del aire acondicionado y cambie sólo si es necesario",
            "Revisar soporte compresor , en especial los tornillos de sujección",
            "Desmonte y monte de compresor de aire de servicio",
            "Repararcion de compresor de aire de servicio",
            "Cambio de empaque ruedas traseras",
            "Reemplazo de filtro secador de aire",
            "Cambio de Valvula de control de frenos de aire de Parqueo",
            "Cambio de valvula SR7",
            "Cambio de Splinder",
            "Desmonte y monte de Bomba Hidraulica Compuerta accionamiento",
            "Desmonte y monte de motor Hidraulico Brazo Movil",
            "Desmonte Y monte de Cilindro Hidrailuco Brazo movil",
            "Desmonte Y monte de Cilindro Hidrailuco Extencion de Pluma",
            "Desmonte Y monte de Cilindro de compuerta Posterior (apertura y cierre)",
            "Desmonte y Monte motor del carrete",
            "Evaluacion de Bomba de Agua (desarme y armado)",
            "Cambio de sellos Bomba de Agua",
            "Cambio de cilindros de la Bomba de Agua",
            "Cambio de Piston bomba de agua",
            "Demonte y Monte Bomba de agua",
            "Cambio de Codo Giratorio",
            "Cambio pasador pivote del Brazo Movil",
            "Reparacion de carrete (cambio de rodamientos y soporte de goma)",
            "Cambio de toma fuerza de accionamineto",
            "Cambio de maguera de succion",
            "Cambio de cojinete de carrete",
            "Desmonte y monte de caja de filtro de compresor de aire de succion",
            "Desmonte y monte filtro compresor de aire",
            "Cambio de valvula de adminsion",
            "Cambio de valvula de descarga",
            "Cambio de valvula de seguridad",
            "Cambio de valvula 3 vias",
            "Cambio de correa de transmision compresor de vacío (Blower)",
            "Cambio de correa de transmision bomba de agua",
            "Desmonte y monte de polea de compresor",
            "Cambio de crucetas eje cardan",
            "Demonte y monte de eje cardan compresor de aire",
            "Cambio de aceite de bomba de agua",
            "Cambio de aceite del compresor",
            "Cambio de filtro hidraulico de retorno y salidad",
            "Cambio de Valvula de descarga",
            "Cambio de valvula de admision",
            "Demonte y monte de tanque de agua",
            "Cambio de indicadores (manometros)",
            "Mantenimiento al sistema electrico control carrete posterior",
            "Reparacion de PTO (Cambio de rodamientos y sellos)",
            "Desmonte y monte de PTO",
            "Cambio de horquilla del PTO",
            "Mantenimiento de Jostick (desmonte / monte y limpieza)",
            "Desmonte y monte de engranaje sin fin",
            "Cambio de cojinete bomba de agua",
            "Cambio de cojinete del blower",
            "Cambio de potenciometro",
            "Mantenimiento al sistema electrico controles laterales",
            "Desmonte y Monte de compresor de aire equipo de trabajo",
            "Cambio de polea de aspirador transmision inferior",
            "Cambio de interruptores basculante, ventilador y bomba de agua",
            "Desmonte Y monte de codo de succion y junta de cierre",
            "Mtto Unidad Valvula de control del carrete",
            "Desmonte Monte y cambio de tuberia de agua alimentacion tanque",
            "Cambio de arnes de sistema de scuccion presion",
            "Desmonte/monte valvula control de carrete. Unidad de valvula 4 carrete",
            "Evaluación / Diagnostico de la Grúa",
            "Desinstalación e Instalación de las Mangueras hidráulicas",
            "Desmonte, Monte Bomba hidráulica",
            "Desmonte y Monte Bloque hidráulico, Cambio de sello de Bloque Hidráulico",
            "Cambio de Válvulas del sistema de la Grúa",
            "Reparación del sistema Eléctrico de la Grúa",
            "Evaluacion sistema Hidraulico",
            "Evaluacion Bomba Hidraulica",
            "Desmonte y Monte de Bomba Hidraulica",
            "Desmonte Y monte de motor Hidraulico",
            "Evalucion y dianostivo sistema electrico",
            "Evaluacion / mtto / calibracion de valvula de preesion trabajo y bloqueos",
            "Reparación de Alternador",
            "Reparación de Motor de arranque"
        ];
        $services = array_unique($items);

        foreach ($services as $value) {
            Service::firstOrCreate([
                'name' => $value
            ]);
        }
    }
}
